name: dotNet Framework Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: SetNugetKey
        run: echo "NUGET_KEY=${{secrets.NUGET_AUTH_TOKEN}}" >> $GITHUB_ENV
      - name: SetGitToken
        run: echo "GIT_TOKEN=${{secrets.GIT_TOKEN}}" >> $GITHUB_ENV
      - uses: nuget/setup-nuget@v1.0.5
        with:
          nuget-api-key: ${{secrets.NUGET_AUTH_TOKEN}}
          nuget-version: 'latest'
