name: dotNet Framework Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: SetNugetKey
        run: echo "NUGET_KEY=${{secrets.NUGET_AUTH_TOKEN}}" >> $GITHUB_ENV
      - name: SetGitToken
        run: echo "GIT_TOKEN=${{secrets.GIT_TOKEN}}" >> $GITHUB_ENV
      - name: SetPassword
        run: echo "GIT_PAS=${{secrets.GIT_PAS}}" >> $GITHUB_ENV
      - uses: nuget/setup-nuget@v1.0.5
        with:
          nuget-api-key: ${{secrets.NUGET_AUTH_TOKEN}}
          nuget-version: 'latest'
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1
        env:
          working-directory: TestOfNuget
      - run: msbuild -t:restore
        working-directory: TestOfNuget
      - run: msbuild -t:build
        working-directory: TestOfNuget
      - name: Nuget Add Source
        run: nuget sources Add -Name "github" -Source https://nuget.pkg.github.com/paolorevit/index.json -UserName paolorevit -password somepass
      - name: Nuget SetAPIKey
        run: nuget setapikey ${{env.GIT_TOKEN}} -Source "github"
      - name: Publish the package to GitHub packages
        working-directory: TestOfNuget
        run: nuget push bin\Debug\*.nupkg -source "github" -SkipDuplicate
